### ISSUE TITLE
Not showing/hiding fields due to JS errors

### ISSUE THREAD

**Issue by thely** [graham73may/bolt-conditional-fields#1]
I'm psyched about this extension - basically this is exactly what I needed that was missing from Bolt.

I tried a couple different ContentType setups using `condition:`, all of which failed to show/hide any fields. In trying to debug the issue, I noticed a few JS errors in the console. As a Bolt newbie, I'm not sure if `var contentTypes = JSON.parse('.......');` in the very first script tag is declared by Bolt or by your extension, but the JSON.parse line is getting a `"missing ) after argument list"` error, making it so `contentTypes` doesn't exist for your `conditional-fields.js` to use.

The JSON on its own validates, but the full line still fails in a JS evaluator. Full line is pasted [on this gist](https://gist.github.com/thely/6f58fc562698a4381d222005d413120c).

e: Using Bolt 3.2.3, bolt-conditional-fields 1.1.0, Chrome 54.0.x

**Comment by graham73may** [comment]
@thely I've had it do this in the past, I'm working to a deadline and haven't had a chance to fully look into it yet. 

The `contentTypes` variable is from this extension.

The issue stems from `json_encode($content_types)` doing some funny business with characters like apostrophes in the .yml file. 

If you're using Chrome, I've managed to find the offending characters in the past by scrolling through the JSON in the elements tab until the formatting changes - usually a speech mark is the cause.

I'll be able to have a deeper look towards the end of this week or feel free to submit a PR if you work it out before then 👍

**Comment by graham73may** [comment]
@thely Just had this on a test site - this is what I meant about scrolling in Chrome inspect for a quickfix:

![image](https://cloud.githubusercontent.com/assets/6642498/20722831/01efbf6e-b660-11e6-83d9-99176f719305.png)

**Comment by graham73may** [comment]
@thely Sorry to spam your inbox... I just tried this on a test site to get around the issue, wondering if it works for you. 

Can you change line 49 of extensions/local/soapbox/conditionalfields/src/ConditionalFieldsExtension.php

```
        $content_types_snippet = (new Snippet())->setCallback('<script>var contentTypes = JSON.parse(\'' . str_replace('\\\\', '\\', json_encode($content_types)) . '\');</script>')
                                                ->setZone(Zone::BACKEND)
                                                ->setLocation(Target::BEFORE_HEAD_JS);

```

to:

```
        $content_types_snippet = (new Snippet())->setCallback('<script>var contentTypes = JSON.parse(\'' . str_replace('\\\\', '\\', json_encode($content_types, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE)) . '\');</script>')
                                                ->setZone(Zone::BACKEND)
                                                ->setLocation(Target::BEFORE_HEAD_JS);

```

and let me know if that helps?

**Comment by thely** [comment]
That fixed it for me! I'll have to test it more a little later, but that's done it for now.

Side note - I don't seem to have an `extensions/local`, just `extensions/vendor`. Not sure if that's because I installed it from the Extend tab in the admin editor, or if it's in local for you because it's your plugin. :)

Either way, thanks a ton!

**Comment by graham73may** [comment]
Sorry I missed that distinction between local and vendor... you are of course correct. Mine's installed as a local extension as I develop the plugin, yours should be vendor. 

I'll add the fix to the repo shortly... You may want to add the flags to the json_encode for taxonomies in the mean time. 

Glad its working for you, if you notice any other bugs please open an issue! (It's a fairly new plugin on a project I'm still working on to give you some context).
