### ISSUE TITLE
Not working in Bolt CMS 3.4.9

### ISSUE THREAD

**Issue by motivecodex** [graham73may/bolt-conditional-fields#11]
Conditional fields 1.3.1 is broken in bolt cms 3.4.9.

**Comment by graham73may** [comment]
Hi @motivecodex,

I've not had a chance to try out some of the newer bolt versions, would you mind adding a screenshot of the console? Hoping it's an easy fix...

**Comment by graham73may** [comment]
Just tested with Bolt 3.5.4 and everything is working as expected. 

Going to close this issue, if you can provide enough information to replicate the problem I'll re-open and investigate. 

Thanks
