### ISSUE TITLE
Error? After installing

### ISSUE THREAD

**Issue by eduardomart** [graham73may/bolt-conditional-fields#12]
`Extension package soapbox/conditionalfields has an invalid class 'Bolt\Extension\Soapbox\ConditionalFields\ConditionalFieldsExtension' and has been skipped.`

It showed up after installing. Not sure what it means.

Bolt 3.5
Tested both PHP 7.1 and 7.2 with same result.

**Comment by graham73may** [comment]
Just tested with Bolt 3.5.4 and everything is working as expected.

Going to close this issue, if you can provide enough information to replicate the problem I'll re-open and investigate.

Thanks
